name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build-platform-linux:
    strategy:
      matrix:
        architecture: [
          {name: 'amd64',   triple: 'x86_64-linux-gnu'},
          {name: 'i686',    triple: 'i686-linux-gnu'},
          {name: 'aarch64', triple: 'aarch64-linux-gnu'},
          {name: 'armhf',   triple: 'arm-linux-gnueabihf'}
        ]

    name: "Building for platform linux-${{matrix.architecture.name}}"
    runs-on: ubuntu-22.04

#    container:
#      image: ubuntu:22.04
#      volumes:
#        - ${{github.workspace}}:${{github.workspace}}
#
#    steps:
#    - name: Install required packages
#      run: apt update && apt install -y clang-15 cmake ninja-build flex bison git
#
#    - name: Install required cross-platform packages (${{ matrix.architecture.triple }})
#      if: matrix.architecture.name != 'amd64'
#      run: apt install -y gcc-12-${{ matrix.architecture.triple }} g++-12-${{ matrix.architecture.triple }}

    steps:
    - name: Settings
      working-directory: ${{github.workspace}}
      run: |
        echo "CMAKE_BUILD_PARALLEL_LEVEL=$(($(nproc) * 16))" >> $GITHUB_ENV
#       echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

    - name: Install required packages
      run: |
        sudo apt update && sudo apt install -y flex bison
  
    - name: Install required cross-platform packages (${{ matrix.architecture.triple }})
      if: matrix.architecture.name != 'amd64'
      run: sudo apt install -y gcc-12-${{ matrix.architecture.triple }} g++-12-${{ matrix.architecture.triple }}
  
    - name: Install dependencies
      working-directory: ${{github.workspace}}
      run: |
        echo Using triple: ${{ matrix.architecture.triple }}
        mkdir -p thirdparties && cd thirdparties
        git clone --depth 1 --single-branch --branch SDL2 https://github.com/libsdl-org/SDL.git
        cmake -B SDL-build \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_C_FLAGS=--target=${{ matrix.architecture.triple }} \
          -DCMAKE_CXX_FLAGS=--target=${{ matrix.architecture.triple }} \
          -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/thirdparties/SDL-install' \
          ./SDL
        cmake --build SDL-build --config Release
        cmake --install SDL-build

    - uses: actions/checkout@v3
      with:
        path: 'source'

    - name: CMake Settings
      run: |
        echo "CMAKE_PARAM=--log-level=VERBOSE \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/install' \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DCMAKE_C_FLAGS=--target=${{ matrix.architecture.triple }} \
        -DCMAKE_CXX_FLAGS=--target=${{ matrix.architecture.triple }} \
        -DGIT_REVISION_BUILD_NUMBER=${{ github.run_number }} \
        -DSDL2_DIR='${{github.workspace}}/thirdparties/SDL-install/lib/cmake/SDL2' \
        -DWITH_CLIENT=1" >> $GITHUB_ENV

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |
        cmake -B ./build ${{ env.CMAKE_PARAM }} ./source
#        cmake -B ./build ${{ env.CMAKE_PARAM }} -DTARGET_GAME_TYPE=0 ./source
#        cmake -B ./buildtt ${{ env.CMAKE_PARAM }} -DTARGET_GAME_TYPE=2 ./source

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
#        cmake --build ${{github.workspace}}/buildtt --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        cd "${{github.workspace}}/build"
        ctest -C ${{env.BUILD_TYPE}}
#        cd "${{github.workspace}}/buildtt"
#        ctest -C ${{env.BUILD_TYPE}}

    - name: Install
      working-directory: ${{github.workspace}}
      # Install to the directory defined in CMAKE_INSTALL_PREFIX
      run: |
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
#        cmake --install ${{github.workspace}}/buildtt --config ${{env.BUILD_TYPE}}
        cp '${{github.workspace}}/thirdparties/SDL-install/lib/libSDL2.so' '${{github.workspace}}/install'

    - uses: actions/upload-artifact@v3
      with:
        name: out-linux-${{matrix.architecture.name}}
        if-no-files-found: error
        path:
          ${{github.workspace}}/install

  build-platform-windows:
    strategy:
      matrix:
        architecture: [
          {name: 'x64',   config: 'x64' },
          {name: 'x86',   config: 'Win32' },
          {name: 'arm64', config: 'ARM64' }
        ]

    name: "Building for platform windows-${{matrix.architecture.name}}"
    runs-on: windows-2022

    steps:
    - name: Settings
      working-directory: ${{github.workspace}}
      run: |
        echo "CMAKE_BUILD_PARALLEL_LEVEL=$((Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors * 16)" >> $GITHUB_ENV

    - name: Install required packages
      working-directory: ${{github.workspace}}
      run: |
        mkdir thirdparties && cd thirdparties
        git clone --depth 1 --single-branch --branch SDL2 https://github.com/libsdl-org/SDL.git
        cmake -B SDL-build -A ${{ matrix.architecture.config }} -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/thirdparties/SDL-install' ./SDL
        cmake --build SDL-build --config Release --parallel
        cmake --install SDL-build
        git clone --depth 1 --single-branch --branch v2.5.25 https://github.com/lexxmark/winflexbison.git
        cmake -B winflexbison-build -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/thirdparties/winflexbison-install' ./winflexbison
        cmake --build winflexbison-build --config Release --parallel
        cmake --install winflexbison-build

    - uses: actions/checkout@v3
      with:
        path: 'source'

    - name: CMake Settings
      run: |
        echo "CMAKE_PARAM=-A ${{ matrix.architecture.config }} `
        --log-level=VERBOSE `
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
        -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/install' `
        -DCMAKE_C_COMPILER=clang `
        -DCMAKE_CXX_COMPILER=clang++ `
        -DGIT_REVISION_BUILD_NUMBER=${{ github.run_number }} `
        -DSDL2_DIR='${{github.workspace}}/thirdparties/SDL-install/cmake' `
        -DBISON_EXECUTABLE='${{github.workspace}}/thirdparties/winflexbison-install/win_bison.exe' `
        -DFLEX_EXECUTABLE='${{github.workspace}}/thirdparties/winflexbison-install/win_flex.exe' `
        -DWITH_CLIENT=1".Replace("`r", "").Replace("`n", "") >> $env:GITHUB_ENV

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |
        cmake -B ./build ${{ env.CMAKE_PARAM }} ./source
#        cmake -B ./build ${{ env.CMAKE_PARAM }} -DTARGET_GAME_TYPE=0 ./source
#        cmake -B ./buildtt ${{ env.CMAKE_PARAM }} -DTARGET_GAME_TYPE=2 ./source

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
#        cmake --build ${{github.workspace}}/buildtt --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        cd "${{github.workspace}}/build"
        ctest -C ${{env.BUILD_TYPE}}
#        cd "${{github.workspace}}/buildtt"
#        ctest -C ${{env.BUILD_TYPE}}

    - name: Install
      working-directory: ${{github.workspace}}
      # Install to the directory defined in CMAKE_INSTALL_PREFIX
      run: |
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
#        cmake --install ${{github.workspace}}/buildtt --config ${{env.BUILD_TYPE}}
        Copy-Item "${{github.workspace}}/thirdparties/SDL-install/bin/*.dll" -Destination "${{github.workspace}}/install"

    - uses: actions/upload-artifact@v3
      with:
        name: out-windows-${{matrix.architecture.name}}
        if-no-files-found: error
        path: |
          ${{github.workspace}}/install
          !${{github.workspace}}/install/**/*.pdb

    - uses: actions/upload-artifact@v3
      with:
        name: out-windows-${{matrix.architecture.name}}-pdb
        if-no-files-found: error
        path: |
          ${{github.workspace}}/install
