name: Publish artifacts

on:
  push:
    tags:
        - "v*.*.*"

env:
  RELEASE_TYPE: ${{ vars.RELEASE_TYPE || 'test' }}
  RELEASE_IS_PRERELEASE: ${{ vars.RELEASE_IS_PRELEASE }}

permissions:
  contents: write

jobs:
  build-all:
   uses: ./.github/workflows/build-cmake.yml

  deploy_all:
    strategy:
      # Set the maximum number of parallel jobs to 1, to avoid a race-condition
      # while creating a new release
      max-parallel: 1
      matrix:
        target_os: [
          'linux-amd64',
          'linux-i686',
          'linux-aarch64',
          'linux-armhf',
          'windows-x64',
          'windows-x86',
          'windows-x64-pdb',
          'windows-x86-pdb',
          'windows-arm64',
          'windows-arm64-pdb'
        ]

    runs-on: ubuntu-22.04
    environment: release
    needs: [build-all]

    env:
      RELEASE_NAME: ${{ github.event.repository.name }}-${{github.ref_name}}-${{matrix.target_os}}

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: 'out-${{matrix.target_os}}'
        path: ${{github.workspace}}/${{matrix.target_os}}

    - name: Zip
      working-directory: ${{github.workspace}}/${{matrix.target_os}}
      run: zip -r ../${{ env.RELEASE_NAME }}.zip ./

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: '${{github.ref_name}}-${{env.RELEASE_TYPE}}'
        prerelease: ${{env.RELEASE_IS_PRERELEASE}}
        files: ${{github.workspace}}/${{ env.RELEASE_NAME }}.zip
