name: Publish artifacts

#on:
#  push:
#    tags:
#        - "v*.*.*"

on: [push]

permissions:
  contents: write

jobs:
#  build-all:
#   uses: ./.github/workflows/cmake.yml

  deploy_windows:
    runs-on: ubuntu-22.04
#    needs: [build-all]

    steps:
#    - uses: actions/download-artifact@v3
#      with:
#        name: 'out-windows-x64'
#        path: ${{github.workspace}}/windows-x64
#
#    - name: Release
#      uses: softprops/action-gh-release@v1
#      with:
#        name: ${{github.ref}}-${{env.RELEASE_TYPE}}
#        prerelease: ${{env.RELEASE_IS_PRERELEASE}}
#        files: ${{github.workspace}}/windows-x64

    - name: Make
      run: mkdir -p ${{github.workspace}}/windows-x64

    - name: Build
      run: echo ${{ github.sha }} > ${{github.workspace}}/windows-x64/test.txt

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}-${{ vars.RELEASE_TYPE || "none" }}
        prerelease: ${{ vars.RELEASE_IS_PRELEASE || true }}
        files: ${{github.workspace}}/windows-x64/test.txt
    
