name: Publish artifacts

on:
  push:
    tags:
        - "v*.*.*"

env:
  RELEASE_TYPE: ${{ vars.RELEASE_TYPE || 'test' }}
  RELEASE_IS_PRERELEASE: ${{ vars.RELEASE_IS_PRELEASE }}

permissions:
  contents: write

jobs:
  build-all:
   uses: ./.github/workflows/cmake.yml

  deploy_windows:
    runs-on: ubuntu-22.04
    environment: release
    needs: [build-all]

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: 'out-windows-x64'
        path: ${{github.workspace}}/windows-x64

    - name: Zip
      working-directory: ${{github.workspace}}/windows-x64
      run: zip -r ../windows-x64.zip .

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{github.ref_name}}-${{env.RELEASE_TYPE}}
        prerelease: ${{env.RELEASE_IS_PRERELEASE}}
        files: ${{github.workspace}}/windows-x64

    
