name: Publish artifacts

on: push

jobs:
  build-all:
    uses: ./.github/workflows/cmake.yml

  deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: 'out-windows-x64'
        path: ${{github.workspace}}/windows-x64

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Release.txt
    
