name: Publish artifacts

on:
  push:
    tags:
        - "v*.*.*"

env:
  RELEASE_TYPE: ${{ vars.RELEASE_TYPE || 'test' }}
  RELEASE_IS_PRERELEASE: ${{ vars.RELEASE_IS_PRELEASE }}

permissions:
  contents: write

jobs:
  build-all:
   uses: ./.github/workflows/build-cmake.yml

  deploy_all:
    strategy:
      matrix:
        target_os: [
          'linux-x64',
          'windows-x64',
          'windows-x86',
          'windows-x64-pdb',
          'windows-x86-pdb'
        ]

    runs-on: ubuntu-22.04
    environment: release
    needs: [build-all]

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: 'out-${{matrix.target_os}}'
        path: ${{github.workspace}}/${{matrix.target_os}}

    - name: Zip
      working-directory: ${{github.workspace}}/${{matrix.target_os}}
      run: zip -r ../${{matrix.target_os}}.zip .

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: '${{github.ref_name}}-${{env.RELEASE_TYPE}}'
        prerelease: ${{env.RELEASE_IS_PRERELEASE}}
        files: ${{github.workspace}}/${{matrix.target_os}}.zip
